import type { KnowledgeJob, KnowledgeJobEvent } from "./types";
import type { KnowledgeWorkspaceDataset } from "./workspace-types";

const now = "2026-06-17T00:00:00.000Z";

const jobs: KnowledgeJob[] = [
  {
    job_id: "demo-ingestion-job",
    workspace_id: "demo-workspace",
    job_type: "ingestion",
    status: "SUCCEEDED",
    payload_hash: "demo-payload-hash",
    idempotency_key: "demo-ingestion",
    attempt: 1,
    max_attempts: 3,
    progress: { stage: "indexing", percent: 100 },
    created_at: "2026-06-16T08:12:00.000Z",
    started_at: "2026-06-16T08:12:04.000Z",
    completed_at: "2026-06-16T08:13:20.000Z",
    error_type: null,
    error_message: null,
    result_reference: { source_id: "src-climate-brief" },
  },
  {
    job_id: "demo-running-ingestion",
    workspace_id: "demo-workspace",
    job_type: "ingestion",
    status: "RUNNING",
    payload_hash: "demo-running-hash",
    idempotency_key: "demo-running",
    attempt: 1,
    max_attempts: 3,
    progress: { stage: "extracting claims", percent: 64 },
    created_at: "2026-06-17T02:08:00.000Z",
    started_at: "2026-06-17T02:08:12.000Z",
    completed_at: null,
    error_type: null,
    error_message: null,
    result_reference: { source_id: "src-quarterly-notes" },
  },
  {
    job_id: "demo-failed-job",
    workspace_id: "demo-workspace",
    job_type: "ingestion",
    status: "FAILED",
    payload_hash: "demo-failed-hash",
    idempotency_key: "demo-failed",
    attempt: 3,
    max_attempts: 3,
    progress: { stage: "acquire source", percent: 20 },
    created_at: "2026-06-15T15:20:00.000Z",
    started_at: "2026-06-15T15:20:03.000Z",
    completed_at: "2026-06-15T15:20:39.000Z",
    error_type: "SOURCE_UNAVAILABLE",
    error_message: "The URL returned 404 during safe acquisition.",
    result_reference: { source_uri: "https://example.invalid/report" },
  },
];

const jobEvents: Record<string, KnowledgeJobEvent[]> = {
  "demo-ingestion-job": [
    { event_id: "evt-1", job_id: "demo-ingestion-job", seq: 1, event_type: "job_queued", payload: {}, created_at: "2026-06-16T08:12:00.000Z" },
    { event_id: "evt-2", job_id: "demo-ingestion-job", seq: 2, event_type: "job_started", payload: { stage: "parse" }, created_at: "2026-06-16T08:12:04.000Z" },
    { event_id: "evt-3", job_id: "demo-ingestion-job", seq: 3, event_type: "job_succeeded", payload: { source_id: "src-climate-brief" }, created_at: "2026-06-16T08:13:20.000Z" },
  ],
  "demo-running-ingestion": [
    { event_id: "evt-run-1", job_id: "demo-running-ingestion", seq: 1, event_type: "job_queued", payload: {}, created_at: "2026-06-17T02:08:00.000Z" },
    { event_id: "evt-run-2", job_id: "demo-running-ingestion", seq: 2, event_type: "job_started", payload: { stage: "extracting claims" }, created_at: "2026-06-17T02:08:12.000Z" },
  ],
  "demo-failed-job": [
    { event_id: "evt-fail-1", job_id: "demo-failed-job", seq: 1, event_type: "job_queued", payload: {}, created_at: "2026-06-15T15:20:00.000Z" },
    { event_id: "evt-fail-2", job_id: "demo-failed-job", seq: 2, event_type: "job_failed", payload: { error_type: "SOURCE_UNAVAILABLE" }, created_at: "2026-06-15T15:20:39.000Z" },
  ],
};

export const demoKnowledgeWorkspace: KnowledgeWorkspaceDataset = {
  sources: [
    {
      id: "src-climate-brief",
      sourceType: "pdf",
      canonicalUri: "deerflow://uploads/climate-transition-brief.pdf",
      title: "Climate Transition Brief",
      author: "Example Research Desk",
      status: "ACTIVE",
      currentRevisionId: "rev-climate-2",
      latestJobId: "demo-ingestion-job",
      claimCount: 4,
      chunkCount: 18,
      updatedAt: "2026-06-16T08:13:20.000Z",
      revisions: [
        {
          id: "rev-climate-1",
          sourceId: "src-climate-brief",
          revisionNumber: 1,
          contentHash: "hash-climate-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-10T10:00:00.000Z",
          chunks: [
            { id: "chunk-climate-1", revisionId: "rev-climate-1", chunkIndex: 0, tokenCount: 180, content: "Earlier policy draft projected lower storage demand.", pageNumber: 4, sectionPath: ["Executive summary"], startOffset: 20, endOffset: 79 },
          ],
        },
        {
          id: "rev-climate-2",
          sourceId: "src-climate-brief",
          revisionNumber: 2,
          previousRevisionId: "rev-climate-1",
          contentHash: "hash-climate-v2",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-16T08:13:20.000Z",
          chunks: [
            { id: "chunk-climate-2", revisionId: "rev-climate-2", chunkIndex: 0, tokenCount: 220, content: "The storage pilot reduced curtailment by 18 percent in Q2 after dispatch rules changed.", pageNumber: 4, sectionPath: ["Executive summary"], startOffset: 42, endOffset: 126 },
            { id: "chunk-climate-3", revisionId: "rev-climate-2", chunkIndex: 1, tokenCount: 170, content: "Grid operators described permitting as the primary schedule risk.", pageNumber: 7, sectionPath: ["Risks"], startOffset: 12, endOffset: 76 },
          ],
        },
      ],
      diff: [
        { id: "diff-1", changeType: "MODIFIED", oldChunkId: "chunk-climate-1", newChunkId: "chunk-climate-2", summary: "Storage impact updated from projected demand to measured curtailment reduction." },
        { id: "diff-2", changeType: "ADDED", newChunkId: "chunk-climate-3", summary: "New permitting risk section added." },
      ],
    },
    {
      id: "src-quarterly-notes",
      sourceType: "markdown",
      canonicalUri: "deerflow://uploads/q2-project-notes.md",
      title: "Q2 Project Notes",
      author: "Demo team",
      status: "INDEXING",
      currentRevisionId: "rev-notes-1",
      latestJobId: "demo-running-ingestion",
      claimCount: 2,
      chunkCount: 9,
      updatedAt: "2026-06-17T02:08:12.000Z",
      revisions: [
        {
          id: "rev-notes-1",
          sourceId: "src-quarterly-notes",
          revisionNumber: 1,
          contentHash: "hash-notes-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "PENDING",
          createdAt: "2026-06-17T02:08:12.000Z",
          chunks: [
            { id: "chunk-notes-1", revisionId: "rev-notes-1", chunkIndex: 0, tokenCount: 140, content: "The decision memo should recommend phased rollout only if customer support staffing is funded.", sectionPath: ["Decision log"], startOffset: 0, endOffset: 96 },
          ],
        },
      ],
      diff: [],
    },
    {
      id: "src-vendor-sheet",
      sourceType: "xlsx",
      canonicalUri: "deerflow://uploads/vendor-comparison.xlsx",
      title: "Vendor Comparison Sheet",
      status: "ACTIVE",
      currentRevisionId: "rev-vendor-1",
      claimCount: 3,
      chunkCount: 6,
      updatedAt: "2026-06-14T13:30:00.000Z",
      revisions: [
        {
          id: "rev-vendor-1",
          sourceId: "src-vendor-sheet",
          revisionNumber: 1,
          contentHash: "hash-vendor-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-14T13:30:00.000Z",
          chunks: [
            { id: "chunk-vendor-1", revisionId: "rev-vendor-1", chunkIndex: 0, tokenCount: 90, content: "Vendor B carries the lowest implementation cost but depends on an immature API.", sectionPath: ["Sheet: Comparison", "Row 12"], startOffset: 0, endOffset: 77 },
          ],
        },
      ],
      diff: [],
    },
    {
      id: "src-broken-url",
      sourceType: "url",
      canonicalUri: "https://example.invalid/report",
      title: "Unavailable Market Report",
      status: "FAILED",
      currentRevisionId: "rev-broken-1",
      latestJobId: "demo-failed-job",
      claimCount: 0,
      chunkCount: 0,
      updatedAt: "2026-06-15T15:20:39.000Z",
      error: "The URL returned 404 during safe acquisition.",
      revisions: [
        {
          id: "rev-broken-1",
          sourceId: "src-broken-url",
          revisionNumber: 1,
          contentHash: "hash-broken",
          parseStatus: "FAILED",
          indexStatus: "FAILED",
          createdAt: "2026-06-15T15:20:39.000Z",
          chunks: [],
        },
      ],
      diff: [],
    },
  ],
  citations: [
    {
      citationId: "cite-storage",
      sourceId: "src-climate-brief",
      revisionId: "rev-climate-2",
      chunkId: "chunk-climate-2",
      evidenceSpanId: "span-storage",
      sourceTitle: "Climate Transition Brief",
      sourceUri: "deerflow://uploads/climate-transition-brief.pdf",
      quotedText: "reduced curtailment by 18 percent in Q2",
      pageNumber: 4,
      sectionPath: ["Executive summary"],
      startOffset: 18,
      endOffset: 58,
      role: "direct",
    },
    {
      citationId: "cite-risk",
      sourceId: "src-climate-brief",
      revisionId: "rev-climate-2",
      chunkId: "chunk-climate-3",
      evidenceSpanId: "span-risk",
      sourceTitle: "Climate Transition Brief",
      sourceUri: "deerflow://uploads/climate-transition-brief.pdf",
      quotedText: "permitting as the primary schedule risk",
      pageNumber: 7,
      sectionPath: ["Risks"],
      startOffset: 25,
      endOffset: 64,
      role: "direct",
    },
    {
      citationId: "cite-staffing",
      sourceId: "src-quarterly-notes",
      revisionId: "rev-notes-1",
      chunkId: "chunk-notes-1",
      evidenceSpanId: "span-staffing",
      sourceTitle: "Q2 Project Notes",
      sourceUri: "deerflow://uploads/q2-project-notes.md",
      quotedText: "phased rollout only if customer support staffing is funded",
      sectionPath: ["Decision log"],
      startOffset: 37,
      endOffset: 96,
      role: "direct",
    },
    {
      citationId: "cite-vendor-api",
      sourceId: "src-vendor-sheet",
      revisionId: "rev-vendor-1",
      chunkId: "chunk-vendor-1",
      evidenceSpanId: "span-vendor-api",
      sourceTitle: "Vendor Comparison Sheet",
      sourceUri: "deerflow://uploads/vendor-comparison.xlsx",
      quotedText: "depends on an immature API",
      sheetName: "Comparison",
      sectionPath: ["Row 12"],
      startOffset: 50,
      endOffset: 77,
      role: "direct",
    },
    {
      citationId: "cite-parent-context",
      sourceId: "src-climate-brief",
      revisionId: "rev-climate-2",
      chunkId: "chunk-climate-3",
      evidenceSpanId: "span-risk-context",
      sourceTitle: "Climate Transition Brief",
      sourceUri: "deerflow://uploads/climate-transition-brief.pdf",
      quotedText: "Risk section includes permitting, queue timing, and interconnection dependencies.",
      pageNumber: 7,
      sectionPath: ["Risks"],
      startOffset: 0,
      endOffset: 80,
      role: "parent_context",
    },
  ],
  entities: [
    { id: "ent-storage", canonicalName: "Storage pilot", entityType: "project", aliases: ["battery pilot"], description: "Grid storage pilot measured in Q2." },
    { id: "ent-permitting", canonicalName: "Permitting", entityType: "risk", aliases: ["approval timing"], description: "Schedule dependency for rollout." },
    { id: "ent-vendor-b", canonicalName: "Vendor B", entityType: "organization", aliases: ["B supplier"], description: "Low cost vendor with API maturity risk." },
    { id: "ent-support", canonicalName: "Customer support staffing", entityType: "resource", aliases: ["support coverage"], description: "Resource gate for phased rollout." },
  ],
  claims: [
    { id: "claim-storage", text: "The storage pilot reduced curtailment by 18 percent in Q2.", normalizedSubject: "Storage pilot", predicate: "reduced", normalizedObject: "curtailment by 18 percent", stance: "SUPPORTS", confidence: 0.92, status: "CURRENT_ACTIVE", citationIds: ["cite-storage"] },
    { id: "claim-risk", text: "Permitting is the primary schedule risk.", normalizedSubject: "Permitting", predicate: "is", normalizedObject: "primary schedule risk", stance: "SUPPORTS", confidence: 0.86, status: "PENDING_CONFLICT_REVIEW", citationIds: ["cite-risk"] },
    { id: "claim-staffing", text: "Phased rollout should proceed only if support staffing is funded.", normalizedSubject: "Phased rollout", predicate: "requires", normalizedObject: "funded support staffing", stance: "SUPPORTS", confidence: 0.8, status: "CURRENT_ACTIVE", citationIds: ["cite-staffing"] },
    { id: "claim-vendor", text: "Vendor B has the lowest implementation cost but an immature API.", normalizedSubject: "Vendor B", predicate: "has tradeoff", normalizedObject: "low cost and API maturity risk", stance: "NEUTRAL", confidence: 0.82, status: "CURRENT_ACTIVE", citationIds: ["cite-vendor-api"] },
  ],
  relations: [
    { id: "rel-storage-risk", sourceEntityId: "ent-storage", targetEntityId: "ent-permitting", relationType: "has_schedule_risk", confidence: 0.77, citationId: "cite-risk" },
    { id: "rel-rollout-support", sourceEntityId: "ent-support", targetEntityId: "ent-storage", relationType: "gates_rollout", confidence: 0.81, citationId: "cite-staffing" },
    { id: "rel-vendor-api", sourceEntityId: "ent-vendor-b", targetEntityId: "ent-storage", relationType: "supports_with_risk", confidence: 0.72, citationId: "cite-vendor-api" },
  ],
  jobs,
  jobEvents,
  searchResults: [
    { id: "result-storage", title: "Storage pilot impact", snippet: "Measured Q2 curtailment reduction supports a phased rollout, but schedule risk remains.", sourceId: "src-climate-brief", revisionId: "rev-climate-2", citationIds: ["cite-storage", "cite-risk", "cite-parent-context"], retrievalChannels: ["Lexical", "Vector", "Graph", "Fused Result"], relatedClaimIds: ["claim-storage", "claim-risk"], relatedEntityIds: ["ent-storage", "ent-permitting"] },
    { id: "result-staffing", title: "Rollout staffing gate", snippet: "Project notes make staffing a condition for rollout, not a background concern.", sourceId: "src-quarterly-notes", revisionId: "rev-notes-1", citationIds: ["cite-staffing"], retrievalChannels: ["Lexical", "Fused Result"], relatedClaimIds: ["claim-staffing"], relatedEntityIds: ["ent-support"] },
  ],
  analysis: {
    query: "Should the storage rollout move forward this quarter?",
    answer: "The evidence supports a phased rollout if support staffing is funded and permitting risk is tracked as a launch gate.",
    supportedFacts: [
      { statement: "The Q2 pilot reduced curtailment by 18 percent.", confidence: 0.92, citationIds: ["cite-storage"] },
      { statement: "Support staffing is an explicit condition for phased rollout.", confidence: 0.8, citationIds: ["cite-staffing"] },
    ],
    inferredConclusions: [
      { statement: "A phased rollout is more defensible than a full launch.", confidence: 0.76, reasoningSummary: "The impact evidence is positive, while risk and staffing constraints argue for gating.", citationIds: ["cite-storage", "cite-risk", "cite-staffing"] },
    ],
    unsupportedClaims: [
      { statement: "Vendor B can absorb all integration work this quarter.", reason: "Only cost and API maturity are present; capacity evidence is missing.", severity: "medium" },
    ],
    unresolvedQuestions: [
      { question: "Is the customer support budget approved?", whyUnresolved: "The notes state the condition but do not show budget approval.", neededEvidence: "Approved staffing budget or operations plan." },
    ],
    sourceIds: ["src-climate-brief", "src-quarterly-notes", "src-vendor-sheet"],
  },
  graph: {
    nodes: [
      { id: "ent-storage", label: "Storage pilot", kind: "entity", x: 110, y: 130, detail: "Measured Q2 pilot." },
      { id: "ent-permitting", label: "Permitting", kind: "entity", x: 360, y: 80, detail: "Primary schedule risk.", citationIds: ["cite-risk"] },
      { id: "claim-storage", label: "18% curtailment reduction", kind: "claim", x: 340, y: 210, detail: "Claim supported by Climate Transition Brief.", citationIds: ["cite-storage"] },
      { id: "src-climate-brief", label: "Climate brief", kind: "source", x: 610, y: 160, detail: "PDF source revision 2." },
      { id: "ent-support", label: "Support staffing", kind: "entity", x: 120, y: 330, detail: "Rollout condition.", citationIds: ["cite-staffing"] },
      { id: "claim-staffing", label: "Staffing gate", kind: "claim", x: 410, y: 350, detail: "Claim from Q2 Project Notes.", citationIds: ["cite-staffing"] },
    ],
    edges: [
      { id: "edge-1", source: "ent-storage", target: "claim-storage", label: "supported by" },
      { id: "edge-2", source: "claim-storage", target: "src-climate-brief", label: "cites" },
      { id: "edge-3", source: "ent-storage", target: "ent-permitting", label: "has risk" },
      { id: "edge-4", source: "ent-support", target: "claim-staffing", label: "gates" },
      { id: "edge-5", source: "claim-staffing", target: "ent-storage", label: "conditions" },
    ],
  },
  conflicts: [
    { id: "conflict-risk", classification: "SCOPE_OR_CONDITION_DIFFERENCE", status: "UNRESOLVED", summary: "Climate brief frames permitting as the main schedule risk while project notes frame staffing as the rollout gate.", claimIds: ["claim-risk", "claim-staffing"], citationIds: ["cite-risk", "cite-staffing"], scopeOrCondition: "Schedule risk vs launch readiness condition", activeClaimId: "claim-staffing", affectedArtifactIds: ["artifact-decision-memo"], recommendedNextStep: "Confirm staffing budget and record whether permitting or support is the launch gate.", updatedAt: "2026-06-17T04:30:00.000Z" },
    { id: "conflict-evidence", classification: "INSUFFICIENT_EVIDENCE", status: "UNRESOLVED", summary: "Vendor capacity has not been verified for the same quarter.", claimIds: ["claim-vendor"], citationIds: ["cite-vendor-api"], scopeOrCondition: "Vendor readiness", activeClaimId: "claim-vendor", affectedArtifactIds: ["artifact-decision-memo"], recommendedNextStep: "Request vendor implementation capacity evidence.", updatedAt: "2026-06-17T05:12:00.000Z" },
  ],
  workflows: [
    { id: "workflow-decision", workflowType: "decision_memo", title: "Decision Memo: Q2 storage rollout", status: "SUCCEEDED", currentStep: "persist_artifact", sourceIds: ["src-climate-brief", "src-quarterly-notes", "src-vendor-sheet"], artifactIds: ["artifact-decision-memo"], updatedAt: "2026-06-17T06:00:00.000Z", steps: [
      { key: "retrieve_evidence", label: "Retrieve evidence", status: "SUCCEEDED", inputSummary: "Storage rollout query", outputSummary: "5 evidence citations" },
      { key: "analyze_evidence", label: "Analyze evidence", status: "SUCCEEDED", inputSummary: "EvidenceContextPack", outputSummary: "Supported facts, inference, unresolved budget question" },
      { key: "persist_artifact", label: "Persist artifact", status: "SUCCEEDED", inputSummary: "Decision memo markdown", outputSummary: "Decision Memo artifact created" },
    ] },
    { id: "workflow-action", workflowType: "knowledge_to_action", title: "Knowledge-to-Action: ask for staffing approval", status: "RUNNING", currentStep: "create_action_draft", sourceIds: ["src-quarterly-notes"], artifactIds: ["artifact-action-draft"], actionDraftId: "approval-staffing", updatedAt: "2026-06-17T07:20:00.000Z", steps: [
      { key: "retrieve_evidence", label: "Retrieve evidence", status: "SUCCEEDED", inputSummary: "Staffing gate", outputSummary: "1 direct citation" },
      { key: "analyze_evidence", label: "Analyze evidence", status: "SUCCEEDED", inputSummary: "Staffing citation", outputSummary: "Draft outreach recommended" },
      { key: "create_action_draft", label: "Create action draft", status: "RUNNING", inputSummary: "Email draft request", outputSummary: "Approval required before execution" },
      { key: "persist_artifact", label: "Persist artifact", status: "PENDING", inputSummary: "Action draft", outputSummary: undefined },
    ] },
  ],
  artifacts: [
    { id: "artifact-decision-memo", artifactType: "decision_memo", title: "Decision Memo: Q2 storage rollout", validationStatus: "VALID", stalenessStatus: "STALE", createdAt: "2026-06-17T06:00:00.000Z", workflowId: "workflow-decision", sourceIds: ["src-climate-brief", "src-quarterly-notes", "src-vendor-sheet"], citationIds: ["cite-storage", "cite-risk", "cite-staffing", "cite-vendor-api"], staleReasons: ["Conflict conflict-risk remains unresolved."], markdown: "## Recommendation\nProceed with a phased rollout only after support staffing is funded.\n\n## Supported facts\n- Q2 pilot reduced curtailment by 18 percent.\n- Project notes require funded support staffing.\n\n## Inference\nA phased rollout limits risk while preserving measured benefit.\n\n## Open evidence\nSupport budget approval is still missing." },
    { id: "artifact-action-draft", artifactType: "action_draft", title: "Action Draft: staffing approval request", validationStatus: "PENDING", stalenessStatus: "CURRENT", createdAt: "2026-06-17T07:20:00.000Z", workflowId: "workflow-action", sourceIds: ["src-quarterly-notes"], citationIds: ["cite-staffing"], staleReasons: [], markdown: "Draft email requesting confirmation that support staffing is funded before phased rollout." },
  ],
  approvals: [
    { id: "approval-staffing", workflowId: "workflow-action", actionType: "fake_email", payloadSummary: "Send a fake email asking operations to confirm support staffing budget.", payloadHash: "sha256:demo-staffing-action", requestedBy: "Demo User", riskLevel: "MEDIUM", status: "AWAITING_APPROVAL", executionStatus: "PENDING", createdAt: "2026-06-17T07:25:00.000Z", audit: ["Draft created from Knowledge-to-Action workflow.", "Payload hash recorded before approval."] },
    { id: "approval-executed", workflowId: "workflow-action", actionType: "fake_task", payloadSummary: "Create a fake follow-up task for vendor API evidence.", payloadHash: "sha256:demo-vendor-task", requestedBy: "Demo User", riskLevel: "LOW", status: "APPROVED", executionStatus: "SUCCEEDED", createdAt: "2026-06-16T11:00:00.000Z", decidedAt: "2026-06-16T11:03:00.000Z", audit: ["Approved by Demo User.", "Fake action executed with idempotency key demo-vendor-task."] },
    { id: "approval-reconcile", workflowId: "workflow-action", actionType: "fake_calendar", payloadSummary: "Hold a fake review slot after missing confirmation.", payloadHash: "sha256:demo-calendar", requestedBy: "Demo User", riskLevel: "HIGH", status: "APPROVED", executionStatus: "RECONCILIATION_REQUIRED", createdAt: "2026-06-15T09:00:00.000Z", decidedAt: "2026-06-15T09:05:00.000Z", audit: ["Approved but fake connector returned ambiguous confirmation.", "Manual reconciliation required."] },
  ],
  activity: [
    { id: "activity-1", type: "ingestion", status: "SUCCEEDED", title: "Climate Transition Brief ingested", linkedHref: "/workspace/knowledge/sources/src-climate-brief", createdAt: "2026-06-16T08:13:20.000Z", detail: "Revision 2 indexed with 18 chunks." },
    { id: "activity-2", type: "workflow", status: "SUCCEEDED", title: "Decision memo workflow completed", linkedHref: "/workspace/knowledge/workflows", createdAt: "2026-06-17T06:00:00.000Z", detail: "Generated Decision Memo artifact." },
    { id: "activity-3", type: "approval", status: "AWAITING_APPROVAL", title: "Staffing approval action requested", linkedHref: "/workspace/knowledge/approvals", createdAt: "2026-06-17T07:25:00.000Z", detail: "Fake email action requires approval." },
    { id: "activity-4", type: "update", status: "UNRESOLVED", title: "Conflict requires review", linkedHref: "/workspace/knowledge/conflicts", createdAt: "2026-06-17T05:12:00.000Z", detail: "Launch gate differs across sources." },
  ],
};

export { now as demoNow };
