import type { KnowledgeJob, KnowledgeJobEvent } from "./types";
import type { KnowledgeWorkspaceDataset } from "./workspace-types";

const now = "2026-06-17T09:40:00.000Z";

const jobs: KnowledgeJob[] = [
  {
    job_id: "job-atlas-architecture-v1",
    workspace_id: "demo-workspace",
    job_type: "ingestion",
    status: "SUCCEEDED",
    payload_hash: "sha256:atlas-architecture-v1",
    idempotency_key: "demo-atlas-architecture-v1",
    attempt: 1,
    max_attempts: 3,
    progress: { stage: "indexed", percent: 100 },
    created_at: "2026-06-14T09:00:00.000Z",
    started_at: "2026-06-14T09:00:06.000Z",
    completed_at: "2026-06-14T09:01:20.000Z",
    error_type: null,
    error_message: null,
    result_reference: { source_id: "src-atlas-architecture" },
  },
  {
    job_id: "job-atlas-architecture-v2",
    workspace_id: "demo-workspace",
    job_type: "ingestion",
    status: "SUCCEEDED",
    payload_hash: "sha256:atlas-architecture-v2",
    idempotency_key: "demo-atlas-architecture-v2",
    attempt: 1,
    max_attempts: 3,
    progress: { stage: "revision diff complete", percent: 100 },
    created_at: "2026-06-16T10:00:00.000Z",
    started_at: "2026-06-16T10:00:05.000Z",
    completed_at: "2026-06-16T10:02:30.000Z",
    error_type: null,
    error_message: null,
    result_reference: { source_id: "src-atlas-architecture", revision_id: "rev-atlas-architecture-2" },
  },
  {
    job_id: "job-atlas-review",
    workspace_id: "demo-workspace",
    job_type: "workflow",
    status: "RUNNING",
    payload_hash: "sha256:atlas-review",
    idempotency_key: "demo-atlas-review",
    attempt: 1,
    max_attempts: 3,
    progress: { stage: "reviewing conflicts", percent: 62 },
    created_at: "2026-06-17T08:30:00.000Z",
    started_at: "2026-06-17T08:30:08.000Z",
    completed_at: null,
    error_type: null,
    error_message: null,
    result_reference: { workflow_id: "workflow-atlas-update-review" },
  },
];

const jobEvents: Record<string, KnowledgeJobEvent[]> = {
  "job-atlas-architecture-v1": [
    { event_id: "evt-atlas-v1-1", job_id: "job-atlas-architecture-v1", seq: 1, event_type: "job_queued", payload: {}, created_at: "2026-06-14T09:00:00.000Z" },
    { event_id: "evt-atlas-v1-2", job_id: "job-atlas-architecture-v1", seq: 2, event_type: "job_started", payload: { stage: "parse" }, created_at: "2026-06-14T09:00:06.000Z" },
    { event_id: "evt-atlas-v1-3", job_id: "job-atlas-architecture-v1", seq: 3, event_type: "job_succeeded", payload: { source_id: "src-atlas-architecture" }, created_at: "2026-06-14T09:01:20.000Z" },
  ],
  "job-atlas-architecture-v2": [
    { event_id: "evt-atlas-v2-1", job_id: "job-atlas-architecture-v2", seq: 1, event_type: "job_queued", payload: {}, created_at: "2026-06-16T10:00:00.000Z" },
    { event_id: "evt-atlas-v2-2", job_id: "job-atlas-architecture-v2", seq: 2, event_type: "revision_diff_detected", payload: { removed: "SQLite", added: "PostgreSQL 16 + pgvector" }, created_at: "2026-06-16T10:01:40.000Z" },
    { event_id: "evt-atlas-v2-3", job_id: "job-atlas-architecture-v2", seq: 3, event_type: "job_succeeded", payload: { revision_id: "rev-atlas-architecture-2" }, created_at: "2026-06-16T10:02:30.000Z" },
  ],
  "job-atlas-review": [
    { event_id: "evt-atlas-review-1", job_id: "job-atlas-review", seq: 1, event_type: "workflow_started", payload: { workflow_id: "workflow-atlas-update-review" }, created_at: "2026-06-17T08:30:08.000Z" },
    { event_id: "evt-atlas-review-2", job_id: "job-atlas-review", seq: 2, event_type: "conflict_review_started", payload: { conflicts: 2 }, created_at: "2026-06-17T08:35:00.000Z" },
  ],
};

export const demoKnowledgeWorkspace: KnowledgeWorkspaceDataset = {
  sources: [
    {
      id: "src-atlas-architecture",
      sourceType: "markdown",
      canonicalUri: "deerflow://uploads/production-architecture.md",
      title: "Project Atlas 生产架构方案",
      author: "Project Atlas Team",
      status: "ACTIVE",
      currentRevisionId: "rev-atlas-architecture-2",
      latestJobId: "job-atlas-architecture-v2",
      claimCount: 2,
      chunkCount: 3,
      updatedAt: "2026-06-16T10:02:30.000Z",
      revisions: [
        {
          id: "rev-atlas-architecture-1",
          sourceId: "src-atlas-architecture",
          revisionNumber: 1,
          contentHash: "hash-atlas-architecture-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-14T09:01:20.000Z",
          chunks: [
            {
              id: "chunk-architecture-v1-storage",
              revisionId: "rev-atlas-architecture-1",
              chunkIndex: 0,
              tokenCount: 88,
              content: "首个公开版本使用 SQLite 保存知识数据，并以本地文件存放索引快照。",
              sectionPath: ["存储方案"],
              startOffset: 0,
              endOffset: 36,
            },
          ],
        },
        {
          id: "rev-atlas-architecture-2",
          sourceId: "src-atlas-architecture",
          revisionNumber: 2,
          previousRevisionId: "rev-atlas-architecture-1",
          contentHash: "hash-atlas-architecture-v2",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-16T10:02:30.000Z",
          chunks: [
            {
              id: "chunk-architecture-v2-storage",
              revisionId: "rev-atlas-architecture-2",
              chunkIndex: 0,
              tokenCount: 112,
              content: "生产环境改用 PostgreSQL 16 与 pgvector，以支持持久化知识、向量检索和并发任务处理。",
              sectionPath: ["存储方案"],
              startOffset: 0,
              endOffset: 49,
            },
            {
              id: "chunk-architecture-v2-risk",
              revisionId: "rev-atlas-architecture-2",
              chunkIndex: 1,
              tokenCount: 96,
              content: "正式上线后的容量、成本和备份策略仍需要真实生产数据验证。",
              sectionPath: ["上线风险"],
              startOffset: 0,
              endOffset: 31,
            },
          ],
        },
      ],
      diff: [
        { id: "diff-atlas-storage-removed", changeType: "REMOVED", oldChunkId: "chunk-architecture-v1-storage", summary: "移除：SQLite" },
        { id: "diff-atlas-storage-added", changeType: "ADDED", newChunkId: "chunk-architecture-v2-storage", summary: "新增：PostgreSQL 16 + pgvector" },
      ],
    },
    {
      id: "src-atlas-meeting-notes",
      sourceType: "markdown",
      canonicalUri: "deerflow://uploads/architecture-meeting-notes.md",
      title: "架构评审会议纪要",
      author: "Architecture Review",
      status: "ACTIVE",
      currentRevisionId: "rev-atlas-meeting-notes-1",
      claimCount: 1,
      chunkCount: 1,
      updatedAt: "2026-06-14T11:30:00.000Z",
      revisions: [
        {
          id: "rev-atlas-meeting-notes-1",
          sourceId: "src-atlas-meeting-notes",
          revisionNumber: 1,
          contentHash: "hash-atlas-meeting-notes-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-14T11:30:00.000Z",
          chunks: [
            {
              id: "chunk-meeting-sqlite",
              revisionId: "rev-atlas-meeting-notes-1",
              chunkIndex: 0,
              tokenCount: 72,
              content: "Project Atlas 首个公开版本继续使用 SQLite，后续根据演示反馈再评估迁移。",
              sectionPath: ["会议结论"],
              startOffset: 0,
              endOffset: 42,
            },
          ],
        },
      ],
      diff: [],
    },
    {
      id: "src-atlas-product-requirements",
      sourceType: "markdown",
      canonicalUri: "deerflow://uploads/product-requirements.md",
      title: "外部通知产品需求",
      author: "Product Team",
      status: "ACTIVE",
      currentRevisionId: "rev-atlas-product-requirements-1",
      claimCount: 1,
      chunkCount: 1,
      updatedAt: "2026-06-15T14:20:00.000Z",
      revisions: [
        {
          id: "rev-atlas-product-requirements-1",
          sourceId: "src-atlas-product-requirements",
          revisionNumber: 1,
          contentHash: "hash-atlas-product-requirements-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-15T14:20:00.000Z",
          chunks: [
            {
              id: "chunk-product-auto-notify",
              revisionId: "rev-atlas-product-requirements-1",
              chunkIndex: 0,
              tokenCount: 70,
              content: "工作流完成后，系统自动向项目成员发送结果通知。",
              sectionPath: ["外部通知"],
              startOffset: 0,
              endOffset: 25,
            },
          ],
        },
      ],
      diff: [],
    },
    {
      id: "src-atlas-security-review",
      sourceType: "markdown",
      canonicalUri: "deerflow://uploads/security-review.md",
      title: "外部行动安全审查",
      author: "Security Review",
      status: "ACTIVE",
      currentRevisionId: "rev-atlas-security-review-1",
      claimCount: 2,
      chunkCount: 2,
      updatedAt: "2026-06-16T15:10:00.000Z",
      revisions: [
        {
          id: "rev-atlas-security-review-1",
          sourceId: "src-atlas-security-review",
          revisionNumber: 1,
          contentHash: "hash-atlas-security-review-v1",
          parseStatus: "SUCCEEDED",
          indexStatus: "SUCCEEDED",
          createdAt: "2026-06-16T15:10:00.000Z",
          chunks: [
            {
              id: "chunk-security-approval",
              revisionId: "rev-atlas-security-review-1",
              chunkIndex: 0,
              tokenCount: 92,
              content: "邮件、日历和任务等外部行动必须先生成草稿，经过明确审批后才能执行。",
              sectionPath: ["审批要求"],
              startOffset: 0,
              endOffset: 38,
            },
            {
              id: "chunk-security-fake-adapter",
              revisionId: "rev-atlas-security-review-1",
              chunkIndex: 1,
              tokenCount: 84,
              content: "公共 Demo 只能使用 Fake Action Adapter，不得发送真实邮件或创建真实日历事件。",
              sectionPath: ["公共演示边界"],
              startOffset: 0,
              endOffset: 45,
            },
          ],
        },
      ],
      diff: [],
    },
  ],
  citations: [
    {
      citationId: "cite-architecture-v1-sqlite",
      sourceId: "src-atlas-architecture",
      revisionId: "rev-atlas-architecture-1",
      chunkId: "chunk-architecture-v1-storage",
      evidenceSpanId: "span-architecture-v1-sqlite",
      sourceTitle: "Project Atlas 生产架构方案",
      sourceUri: "deerflow://uploads/production-architecture.md",
      quotedText: "首个公开版本使用 SQLite 保存知识数据",
      sectionPath: ["存储方案"],
      startOffset: 0,
      endOffset: 20,
      role: "direct",
    },
    {
      citationId: "cite-architecture-v2-postgres",
      sourceId: "src-atlas-architecture",
      revisionId: "rev-atlas-architecture-2",
      chunkId: "chunk-architecture-v2-storage",
      evidenceSpanId: "span-architecture-v2-postgres",
      sourceTitle: "Project Atlas 生产架构方案",
      sourceUri: "deerflow://uploads/production-architecture.md",
      quotedText: "生产环境改用 PostgreSQL 16 与 pgvector",
      sectionPath: ["存储方案"],
      startOffset: 0,
      endOffset: 28,
      role: "direct",
    },
    {
      citationId: "cite-architecture-v2-capability",
      sourceId: "src-atlas-architecture",
      revisionId: "rev-atlas-architecture-2",
      chunkId: "chunk-architecture-v2-storage",
      evidenceSpanId: "span-architecture-v2-capability",
      sourceTitle: "Project Atlas 生产架构方案",
      sourceUri: "deerflow://uploads/production-architecture.md",
      quotedText: "支持持久化知识、向量检索和并发任务处理",
      sectionPath: ["存储方案"],
      startOffset: 29,
      endOffset: 49,
      role: "direct",
    },
    {
      citationId: "cite-meeting-sqlite",
      sourceId: "src-atlas-meeting-notes",
      revisionId: "rev-atlas-meeting-notes-1",
      chunkId: "chunk-meeting-sqlite",
      evidenceSpanId: "span-meeting-sqlite",
      sourceTitle: "架构评审会议纪要",
      sourceUri: "deerflow://uploads/architecture-meeting-notes.md",
      quotedText: "Project Atlas 首个公开版本继续使用 SQLite",
      sectionPath: ["会议结论"],
      startOffset: 0,
      endOffset: 27,
      role: "direct",
    },
    {
      citationId: "cite-product-auto-notify",
      sourceId: "src-atlas-product-requirements",
      revisionId: "rev-atlas-product-requirements-1",
      chunkId: "chunk-product-auto-notify",
      evidenceSpanId: "span-product-auto-notify",
      sourceTitle: "外部通知产品需求",
      sourceUri: "deerflow://uploads/product-requirements.md",
      quotedText: "工作流完成后，系统自动向项目成员发送结果通知",
      sectionPath: ["外部通知"],
      startOffset: 0,
      endOffset: 24,
      role: "direct",
    },
    {
      citationId: "cite-security-approval",
      sourceId: "src-atlas-security-review",
      revisionId: "rev-atlas-security-review-1",
      chunkId: "chunk-security-approval",
      evidenceSpanId: "span-security-approval",
      sourceTitle: "外部行动安全审查",
      sourceUri: "deerflow://uploads/security-review.md",
      quotedText: "外部行动必须先生成草稿，经过明确审批后才能执行",
      sectionPath: ["审批要求"],
      startOffset: 10,
      endOffset: 38,
      role: "direct",
    },
    {
      citationId: "cite-security-fake-adapter",
      sourceId: "src-atlas-security-review",
      revisionId: "rev-atlas-security-review-1",
      chunkId: "chunk-security-fake-adapter",
      evidenceSpanId: "span-security-fake-adapter",
      sourceTitle: "外部行动安全审查",
      sourceUri: "deerflow://uploads/security-review.md",
      quotedText: "公共 Demo 只能使用 Fake Action Adapter，不得发送真实邮件或创建真实日历事件",
      sectionPath: ["公共演示边界"],
      startOffset: 0,
      endOffset: 44,
      role: "direct",
    },
    {
      citationId: "cite-architecture-open-risk",
      sourceId: "src-atlas-architecture",
      revisionId: "rev-atlas-architecture-2",
      chunkId: "chunk-architecture-v2-risk",
      evidenceSpanId: "span-architecture-open-risk",
      sourceTitle: "Project Atlas 生产架构方案",
      sourceUri: "deerflow://uploads/production-architecture.md",
      quotedText: "容量、成本和备份策略仍需要真实生产数据验证",
      sectionPath: ["上线风险"],
      startOffset: 5,
      endOffset: 31,
      role: "direct",
    },
  ],
  entities: [
    { id: "ent-project-atlas", canonicalName: "Project Atlas", entityType: "project", aliases: ["个人知识智能体上线方案"], description: "个人知识智能体生产部署和外部行动策略演示项目。" },
    { id: "ent-postgresql-pgvector", canonicalName: "PostgreSQL 16 + pgvector", entityType: "technology", aliases: ["PostgreSQL", "pgvector"], description: "Project Atlas 当前生产知识存储和向量检索方案。" },
    { id: "ent-sqlite", canonicalName: "SQLite", entityType: "technology", aliases: ["local sqlite"], description: "Project Atlas 初版和旧会议纪要中的存储方案。" },
    { id: "ent-fake-action-adapter", canonicalName: "Fake Action Adapter", entityType: "adapter", aliases: ["伪执行适配器"], description: "公共 Demo 中用于避免真实外部副作用的动作适配器。" },
  ],
  claims: [
    { id: "claim-architecture-v1-sqlite", text: "首个公开版本使用 SQLite 保存知识数据。", normalizedSubject: "Project Atlas", predicate: "uses_storage", normalizedObject: "SQLite", stance: "SUPPORTS", confidence: 0.82, status: "SUPERSEDED", citationIds: ["cite-architecture-v1-sqlite"] },
    { id: "claim-architecture-v2-postgres", text: "Project Atlas 当前生产架构采用 PostgreSQL 16 和 pgvector。", normalizedSubject: "Project Atlas", predicate: "uses_storage", normalizedObject: "PostgreSQL 16 + pgvector", stance: "SUPPORTS", confidence: 0.95, status: "CURRENT_ACTIVE", citationIds: ["cite-architecture-v2-postgres"] },
    { id: "claim-meeting-sqlite", text: "Project Atlas 首个公开版本继续使用 SQLite。", normalizedSubject: "Project Atlas", predicate: "uses_storage", normalizedObject: "SQLite", stance: "SUPPORTS", confidence: 0.84, status: "HISTORICAL", citationIds: ["cite-meeting-sqlite"] },
    { id: "claim-product-auto-notify", text: "工作流完成后，系统自动向项目成员发送结果通知。", normalizedSubject: "外部通知", predicate: "executes", normalizedObject: "自动发送通知", stance: "SUPPORTS", confidence: 0.86, status: "PENDING_CONFLICT_REVIEW", citationIds: ["cite-product-auto-notify"] },
    { id: "claim-security-approval", text: "邮件、日历和任务等外部行动必须先生成草稿，经过明确审批后才能执行。", normalizedSubject: "外部行动", predicate: "requires", normalizedObject: "审批后执行", stance: "SUPPORTS", confidence: 0.94, status: "CURRENT_ACTIVE", citationIds: ["cite-security-approval"] },
    { id: "claim-security-fake-adapter", text: "公共 Demo 只能使用 Fake Action Adapter，不得发送真实邮件或创建真实日历事件。", normalizedSubject: "公共 Demo", predicate: "uses_adapter", normalizedObject: "Fake Action Adapter", stance: "SUPPORTS", confidence: 0.97, status: "CURRENT_ACTIVE", citationIds: ["cite-security-fake-adapter"] },
  ],
  relations: [
    { id: "rel-atlas-current-storage", sourceEntityId: "ent-project-atlas", targetEntityId: "ent-postgresql-pgvector", relationType: "current_storage", confidence: 0.95, citationId: "cite-architecture-v2-postgres" },
    { id: "rel-atlas-old-storage", sourceEntityId: "ent-project-atlas", targetEntityId: "ent-sqlite", relationType: "superseded_storage", confidence: 0.84, citationId: "cite-meeting-sqlite" },
    { id: "rel-demo-fake-adapter", sourceEntityId: "ent-project-atlas", targetEntityId: "ent-fake-action-adapter", relationType: "safe_demo_adapter", confidence: 0.97, citationId: "cite-security-fake-adapter" },
  ],
  jobs,
  jobEvents,
  searchResults: [
    {
      id: "result-atlas-current-database",
      title: "Project Atlas 的生产数据库方案",
      snippet: "当前架构方案显示，Project Atlas 生产环境改用 PostgreSQL 16 与 pgvector，以支持持久化知识、向量检索和并发任务处理。",
      sourceId: "src-atlas-architecture",
      revisionId: "rev-atlas-architecture-2",
      citationIds: ["cite-architecture-v2-postgres", "cite-architecture-v2-capability"],
      retrievalChannels: ["Lexical", "Vector", "Graph", "Fused Result"],
      relatedClaimIds: ["claim-architecture-v2-postgres"],
      relatedEntityIds: ["ent-project-atlas", "ent-postgresql-pgvector"],
    },
    {
      id: "result-atlas-notification-policy",
      title: "外部通知是否可以自动发送",
      snippet: "产品需求希望工作流完成后自动通知项目成员，但安全审查要求外部行动必须先生成草稿并经过审批。",
      sourceId: "src-atlas-security-review",
      revisionId: "rev-atlas-security-review-1",
      citationIds: ["cite-product-auto-notify", "cite-security-approval", "cite-security-fake-adapter"],
      retrievalChannels: ["Lexical", "Vector", "Fused Result"],
      relatedClaimIds: ["claim-product-auto-notify", "claim-security-approval", "claim-security-fake-adapter"],
      relatedEntityIds: ["ent-project-atlas", "ent-fake-action-adapter"],
    },
  ],
  analysis: {
    query: "Project Atlas 的生产数据库方案是什么？",
    answer: "Project Atlas 当前生产架构采用 PostgreSQL 16 和 pgvector。该结论来自 production-architecture.md 的 Revision 2；旧会议纪要中的 SQLite 结论应作为历史上下文处理。",
    supportedFacts: [
      { statement: "Project Atlas 当前生产架构采用 PostgreSQL 16 和 pgvector。", confidence: 0.95, citationIds: ["cite-architecture-v2-postgres"] },
    ],
    inferredConclusions: [
      { statement: "这一变化可能是为了支持持久化知识、向量检索和并发任务处理。", confidence: 0.78, reasoningSummary: "Revision 2 明确列出这些能力目标，但没有声称这是唯一原因，因此标记为推断。", citationIds: ["cite-architecture-v2-capability"] },
    ],
    unsupportedClaims: [
      { statement: "PostgreSQL 方案已经通过大规模生产流量验证。", reason: "当前来源只说明生产化导向和待验证风险，没有提供大规模流量验证证据。", severity: "high" },
    ],
    unresolvedQuestions: [
      { question: "正式上线后的容量、成本和备份策略是否已经验证？", whyUnresolved: "架构方案明确这些问题仍需要真实生产数据验证。", neededEvidence: "上线后的容量、成本、备份演练和恢复指标。" },
    ],
    sourceIds: ["src-atlas-architecture", "src-atlas-meeting-notes"],
  },
  graph: {
    nodes: [
      { id: "ent-project-atlas", label: "Project Atlas", kind: "entity", x: 110, y: 160, detail: "个人知识智能体上线方案。" },
      { id: "claim-architecture-v2-postgres", label: "当前使用 PostgreSQL 16 + pgvector", kind: "claim", x: 360, y: 110, detail: "Revision 2 支持的当前主张。", citationIds: ["cite-architecture-v2-postgres"] },
      { id: "claim-meeting-sqlite", label: "旧会议纪要保留 SQLite", kind: "claim", x: 360, y: 250, detail: "历史上下文，与当前版本形成旧知识冲突。", citationIds: ["cite-meeting-sqlite"] },
      { id: "src-atlas-architecture", label: "生产架构方案", kind: "source", x: 610, y: 110, detail: "production-architecture.md Revision 2。" },
      { id: "src-atlas-security-review", label: "安全审查", kind: "source", x: 610, y: 320, detail: "要求审批与 Fake Action Adapter。" },
      { id: "claim-security-approval", label: "外部行动先审批", kind: "claim", x: 360, y: 360, detail: "安全审查支持的行动边界。", citationIds: ["cite-security-approval"] },
    ],
    edges: [
      { id: "edge-atlas-current-storage", source: "ent-project-atlas", target: "claim-architecture-v2-postgres", label: "当前方案" },
      { id: "edge-current-cites-source", source: "claim-architecture-v2-postgres", target: "src-atlas-architecture", label: "引用" },
      { id: "edge-old-conflict", source: "claim-meeting-sqlite", target: "claim-architecture-v2-postgres", label: "旧知识更新" },
      { id: "edge-security-source", source: "claim-security-approval", target: "src-atlas-security-review", label: "引用" },
    ],
  },
  conflicts: [
    {
      id: "conflict-atlas-storage-update",
      classification: "TEMPORAL_UPDATE",
      status: "UNRESOLVED",
      summary: "数据库方案的旧知识更新：当前架构方案采用 PostgreSQL 16 + pgvector，旧会议纪要仍保留 SQLite。",
      claimIds: ["claim-architecture-v2-postgres", "claim-meeting-sqlite"],
      citationIds: ["cite-architecture-v2-postgres", "cite-meeting-sqlite"],
      scopeOrCondition: "旧知识与当前版本不一致",
      activeClaimId: "claim-architecture-v2-postgres",
      affectedArtifactIds: ["artifact-atlas-initial-storage-memo"],
      recommendedNextStep: "确认 Revision 2 为当前方案，并将基于 SQLite 的旧产物标记为过期。",
      updatedAt: "2026-06-16T10:20:00.000Z",
    },
    {
      id: "conflict-atlas-notification-approval",
      classification: "DIRECT_CONTRADICTION",
      status: "UNRESOLVED",
      summary: "外部通知的自动执行与审批要求冲突：产品需求要求自动发送，安全审查要求先审批。",
      claimIds: ["claim-product-auto-notify", "claim-security-approval"],
      citationIds: ["cite-product-auto-notify", "cite-security-approval"],
      scopeOrCondition: "自动执行 vs 审批控制",
      activeClaimId: "claim-security-approval",
      affectedArtifactIds: ["artifact-atlas-current-storage-memo"],
      recommendedNextStep: "保留通知草稿，进入审批流程后再通过 Fake Action Adapter 执行。",
      updatedAt: "2026-06-17T08:10:00.000Z",
    },
  ],
  workflows: [
    {
      id: "workflow-atlas-storage-decision",
      workflowType: "decision_memo",
      title: "Project Atlas 生产存储决策",
      status: "COMPLETED",
      currentStep: "persist_artifact",
      sourceIds: ["src-atlas-architecture", "src-atlas-meeting-notes"],
      artifactIds: ["artifact-atlas-current-storage-memo"],
      updatedAt: "2026-06-16T11:20:00.000Z",
      steps: [
        { key: "retrieve_evidence", label: "检索架构证据", status: "SUCCEEDED", inputSummary: "生产数据库方案", outputSummary: "找到 Revision 2 的 PostgreSQL 16 + pgvector 证据" },
        { key: "analyze_conflict", label: "对比旧会议结论", status: "SUCCEEDED", inputSummary: "SQLite 与 PostgreSQL 主张", outputSummary: "识别旧知识更新" },
        { key: "persist_artifact", label: "生成决策备忘录", status: "COMPLETED", inputSummary: "Decision Memo", outputSummary: "选择 PostgreSQL 16 + pgvector" },
      ],
    },
    {
      id: "workflow-atlas-update-review",
      workflowType: "knowledge_update_review",
      title: "生产架构版本更新审查",
      status: "RUNNING",
      currentStep: "review_conflicts",
      sourceIds: ["src-atlas-architecture", "src-atlas-meeting-notes", "src-atlas-security-review"],
      artifactIds: ["artifact-atlas-initial-storage-memo"],
      updatedAt: "2026-06-17T08:35:00.000Z",
      steps: [
        { key: "compare_revisions", label: "比较新旧版本", status: "SUCCEEDED", inputSummary: "SQLite → PostgreSQL 16 + pgvector", outputSummary: "检测到主要存储方案变化" },
        { key: "mark_stale", label: "标记过期产物", status: "SUCCEEDED", inputSummary: "初版存储决策备忘录", outputSummary: "旧产物已标记为过期" },
        { key: "review_conflicts", label: "审查冲突", status: "RUNNING", inputSummary: "旧知识与行动审批冲突", outputSummary: "等待人工确认处理策略" },
      ],
    },
    {
      id: "workflow-atlas-notify-change",
      workflowType: "knowledge_to_action",
      title: "向项目成员通知架构变更",
      status: "REQUIRES_APPROVAL",
      currentStep: "await_approval",
      sourceIds: ["src-atlas-architecture", "src-atlas-security-review"],
      artifactIds: ["artifact-atlas-current-storage-memo"],
      actionDraftId: "approval-atlas-notification-email",
      updatedAt: "2026-06-17T09:25:00.000Z",
      steps: [
        { key: "draft_message", label: "生成通知草稿", status: "SUCCEEDED", inputSummary: "架构变更摘要", outputSummary: "邮件草稿已生成" },
        { key: "safety_check", label: "检查行动边界", status: "SUCCEEDED", inputSummary: "外部行动安全审查", outputSummary: "必须先审批，公共 Demo 只能使用 Fake Action Adapter" },
        { key: "await_approval", label: "等待审批", status: "REQUIRES_APPROVAL", inputSummary: "发送 Project Atlas 架构变更通知", outputSummary: "等待审批后才能执行" },
      ],
    },
  ],
  artifacts: [
    {
      id: "artifact-atlas-current-storage-memo",
      artifactType: "Decision Memo",
      title: "Project Atlas 生产存储决策备忘录",
      validationStatus: "VALID",
      stalenessStatus: "CURRENT",
      createdAt: "2026-06-16T11:20:00.000Z",
      workflowId: "workflow-atlas-storage-decision",
      sourceIds: ["src-atlas-architecture", "src-atlas-security-review"],
      citationIds: ["cite-architecture-v2-postgres", "cite-architecture-v2-capability", "cite-architecture-open-risk", "cite-security-approval"],
      staleReasons: [],
      markdown: "## 结论\nProject Atlas 生产环境采用 PostgreSQL 16 + pgvector。\n\n## 证据来源\n- production-architecture.md Revision 2 明确更新为 PostgreSQL 16 + pgvector。\n- 该方案用于支持持久化知识、向量检索和并发任务处理。\n\n## 已知风险\n- 容量、成本和备份策略仍需要真实生产数据验证。\n\n## 后续行动\n- 通知项目成员架构变更，但外部通知必须先进入审批流程。",
    },
    {
      id: "artifact-atlas-initial-storage-memo",
      artifactType: "Decision Memo",
      title: "Project Atlas 初版存储决策备忘录",
      validationStatus: "VALID",
      stalenessStatus: "STALE",
      createdAt: "2026-06-14T12:00:00.000Z",
      workflowId: "workflow-atlas-update-review",
      sourceIds: ["src-atlas-architecture", "src-atlas-meeting-notes"],
      citationIds: ["cite-architecture-v1-sqlite", "cite-meeting-sqlite"],
      staleReasons: ["production-architecture.md 已从 Revision 1 更新至 Revision 2，原产物仍基于 SQLite 方案。"],
      markdown: "## 原始结论\nProject Atlas 初版使用 SQLite 保存知识数据。\n\n## 过期原因\nproduction-architecture.md 已从 Revision 1 更新至 Revision 2，当前方案改为 PostgreSQL 16 + pgvector。",
    },
  ],
  approvals: [
    {
      id: "approval-atlas-notification-email",
      workflowId: "workflow-atlas-notify-change",
      actionType: "EMAIL_DRAFT",
      payloadSummary: "发送 Project Atlas 架构变更通知：当前生产方案已从 SQLite 更新为 PostgreSQL 16 + pgvector。",
      payloadHash: "sha256:atlas-notification-email",
      requestedBy: "Demo User",
      riskLevel: "MEDIUM",
      status: "AWAITING_APPROVAL",
      executionStatus: "PENDING",
      createdAt: "2026-06-17T09:25:00.000Z",
      audit: ["行动草稿由 Knowledge-to-Action 工作流生成。", "安全审查要求审批通过后才能执行。", "公共 Demo 不会发送真实邮件。"],
    },
    {
      id: "approval-atlas-export-memo",
      workflowId: "workflow-atlas-storage-decision",
      actionType: "EXPORT_ARTIFACT",
      payloadSummary: "导出 Project Atlas 生产存储决策备忘录。Adapter: Fake Action Adapter。",
      payloadHash: "sha256:atlas-export-memo",
      requestedBy: "Demo User",
      riskLevel: "LOW",
      status: "APPROVED",
      executionStatus: "SUCCEEDED",
      createdAt: "2026-06-16T11:30:00.000Z",
      decidedAt: "2026-06-16T11:32:00.000Z",
      audit: ["Approved by Demo User.", "Fake Action Adapter 记录了导出动作。", "没有执行真实外部副作用。"],
    },
  ],
  activity: [
    { id: "activity-atlas-1", type: "ingestion", status: "SUCCEEDED", title: "导入生产架构方案 Revision 1", linkedHref: "/workspace/knowledge/sources/src-atlas-architecture", createdAt: "2026-06-14T09:01:20.000Z", detail: "production-architecture.md 初版包含 SQLite 方案。" },
    { id: "activity-atlas-2", type: "ingestion", status: "SUCCEEDED", title: "导入旧会议纪要", linkedHref: "/workspace/knowledge/sources/src-atlas-meeting-notes", createdAt: "2026-06-14T11:30:00.000Z", detail: "architecture-meeting-notes.md 保留 SQLite 结论。" },
    { id: "activity-atlas-3", type: "artifact", status: "CURRENT_THEN", title: "生成初版决策备忘录", linkedHref: "/workspace/knowledge/artifacts", createdAt: "2026-06-14T12:00:00.000Z", detail: "初版产物基于 SQLite 方案。" },
    { id: "activity-atlas-4", type: "ingestion", status: "SUCCEEDED", title: "导入生产架构方案 Revision 2", linkedHref: "/workspace/knowledge/sources/src-atlas-architecture", createdAt: "2026-06-16T10:02:30.000Z", detail: "当前版本改为 PostgreSQL 16 + pgvector。" },
    { id: "activity-atlas-5", type: "update", status: "DETECTED", title: "检测到架构知识变化", linkedHref: "/workspace/knowledge/sources/src-atlas-architecture", createdAt: "2026-06-16T10:20:00.000Z", detail: "SQLite → PostgreSQL 16 + pgvector。" },
    { id: "activity-atlas-6", type: "artifact", status: "STALE", title: "旧产物被标记为过期", linkedHref: "/workspace/knowledge/artifacts", createdAt: "2026-06-16T10:30:00.000Z", detail: "初版决策备忘录仍基于 SQLite 方案。" },
    { id: "activity-atlas-7", type: "update", status: "UNRESOLVED", title: "检测外部行动策略冲突", linkedHref: "/workspace/knowledge/conflicts", createdAt: "2026-06-17T08:10:00.000Z", detail: "产品需求要求自动发送，安全审查要求先审批。" },
    { id: "activity-atlas-8", type: "workflow", status: "RUNNING", title: "启动知识更新审查", linkedHref: "/workspace/knowledge/workflows", createdAt: "2026-06-17T08:30:00.000Z", detail: "审查版本更新、过期产物和冲突处理。" },
    { id: "activity-atlas-9", type: "approval", status: "AWAITING_APPROVAL", title: "生成架构变更通知草稿", linkedHref: "/workspace/knowledge/approvals", createdAt: "2026-06-17T09:25:00.000Z", detail: "通知草稿等待审批，不会发送真实邮件。" },
    { id: "activity-atlas-10", type: "approval", status: "PENDING", title: "等待审批", linkedHref: "/workspace/knowledge/approvals", createdAt: "2026-06-17T09:30:00.000Z", detail: "外部通知必须审批后才能通过 Fake Action Adapter 执行。" },
  ],
};

export { now as demoNow };
